### ISSUE TITLE
Key Frames

### ISSUE THREAD

**Issue by voltzlader** [Romulion/LMD_Animation_Loader#4]
I downloaded this, and I got the animations working.. somewhat. They're really janky and seems to be only importing the keyframes. I understand that there needs to be a keyframe on each frame for importing, but even doing that isn't working and I've been trying at this for a few days. Do you have any pointers / can you explain how to get this working better in more detail? Thanks

Sent an example of the error:

https://user-images.githubusercontent.com/83433948/116630521-4d403300-a921-11eb-8a85-b3ccad32b531.mov

**Comment by Romulion** [comment]
For animation game uses keyframes with timestamps. Since blender uses keyframes with fixed interval, I use linear interpolation on 60fps. this might result to small animation bugs.
For me it just looks OK.
I see you run sync_move_player animation. This type of animation usually have data for camera movement (move_player_cam).
For cooler look developers can distort animation or dont use some bones for better look on centrain perspective.

**Comment by ZoruaLoL** [comment]
Certain bones seem to be off-centered, including the root bone but particularly when it's for accessory items like Ghetsis' cane or Archie's anchor and many others.

![ghetsis](https://user-images.githubusercontent.com/49895285/147020675-b4723b80-d9e6-42ce-a538-78b88d8cdeb7.png)
![archie](https://user-images.githubusercontent.com/49895285/147020907-6ec8de1c-816d-4c9d-bd3e-a3481f0cd39f.png)
![bugsy](https://user-images.githubusercontent.com/49895285/147026146-6e23d9a4-1ecd-49dd-bf80-c5ae0dbebad5.png)

Facial animations seem to be have a lot of clipping on the mouths or poseable brows.
![hau](https:
![agatha](https://user-images.githubusercontent.com/49895285/147026710-04bc1824-fcda-48f4-8d0d-c6684f887dc7.png)
//user-images.githubusercontent.com/49895285/147026487-0f6be4fc-185e-429c-9c2a-63e99f40da02.png)

And since update 2.10.0 or prior character movement appears to be pretty jerky and incorrectly timed.

https://user-images.githubusercontent.com/49895285/147030134-f97c8e87-26da-4eaa-8149-1035096ee110.mp4

There's this Maxscript for 3DS Max which present none of the above issues by killercracker. It would be worth checking out for its implementation:
https://drive.google.com/drive/folders/1wB_AeF7tR47aeHdH3HCGNovklMgxVv8J

(Exported as .fbx)
https://user-images.githubusercontent.com/49895285/147031213-2b461502-a75f-488c-a34c-35ac56b56f4d.mp4

Also, aside of the needed overhaul the script needs to be updated to Blender 3.0-

**Comment by Romulion** [comment]
Fixed issues with face, and other animations that involve translation (didnt propertly convert bone to local coordanates space)
Although remove interpolation. animation now smoother.
Test with Blender 3.1, works well
